# For more info on HTTP files go to https://aka.ms/vs/httpfile
las claves son 

DUEÑO
dueno@futbolito.cl
dueno123

ADMINISTRADOR
Email: admin2@futbolito.cl
Contraseña: admin456

desarrollador
devteam01@futbolito.cl
devteam01